name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/setup-nasm@v1.4.0
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - uses: seanmiddleditch/gha-setup-vsdevenv@v4
    
    - name: Configure & Build
      if: matrix.os == 'windows-latest'
      run: |
        cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_LINKER=link -DCMAKE_AR=lib
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Configure & Build
      if: matrix.os != 'windows-latest'
      run: |
        cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
